app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5433/user_registration
    username: postgres
    password: user-registration

spring:
  application:
    name: USER-REGISTRATION-SERVICE
  zipkin:
    base-url: http://localhost:8093/

server:
  port : 8081

jwt:
  secret-key: secretkey123456789

logging:
  file:
    name: C:/Users/stein/Desktop/project-work/ELK-Stack/logs/user-registration.log
