app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5433/user-registration
    username: postgres
    password: user-registration

spring:
  application:
    name: user-registration-service
  zipkin:
    base-url: http://127.0.0.1:9411/

server:
  port : 8081

jwt:
  secret-key: secretkey123456789