app:
  datasource:
    jdbc-url: jdbc:postgresql://user-registration-database:5433/user_registration
    username: postgres
    password: postgres

spring:
  application:
    name: USER-REGISTRATION-SERVICE
  zipkin:
    base-url: http://zipkin:8093/
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port : 8081

jwt:
  secret-key: secretkey123456789

#logging:
  #file:
    #path: logs
    #name: user-registration.log
    #name: C:/Users/stein/Desktop/project-work/ELK-Stack/logs/user-registration.log
