app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5434/sales_department
    username: postgres
    password: sales-department
    pool-size: 30

server:
  port : 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka