app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5435/manufacturing_department
    username: postgres
    password: manufacturing-department
    pool-size: 30

server:
  port : 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka