version: '3'
services:
  service-discovery:
    image: michaelxsteinertxcontainer/project-work/microservice-docker-service-discovery:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
  config-server:
    image: michaelxsteinertxcontainer/project-work/microservice-docker-config-server:0.0.1-SNAPSHOT
    volumes:
      - ./config-repository:/var/config-data
    environment:
      - JAVA_OPTS=
         -DEUREKA_SERVER=http://service-discovery:8761/eureka
         -Dspring.cloud.config.server.native.searchLocations=/var/config-data
    depends_on:
      - service-discovery
    ports:
      - 8888:8888
  gateway-service:
    image: michaelxsteinertxcontainer/project-work/microservice-docker-gateway-service:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://service-discovery:8761/eureka
    restart: on-failure
    depends_on:
      - service-discovery
      - config-server
    ports:
      - 8080:8080