spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: user_registration_route
          uri: lb://USER-REGISTRATION-SERVICE
          predicates:
            - Path=/user-registration/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-REGISTRATION-SERVICE-FALLBACK
                fallbackuri: forward:/userRegistrationServiceFallBack
        - id: user_management_route
          uri: lb://USER-MANAGEMENT-SERVICE
          predicates:
            - Path=/user-manegement/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-MANAGEMENT-SERVICE-FALLBACK
                fallbackuri: forward:/userManagementServiceFallBack

server:
  port: 8091

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
