spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: customer_route
          uri: lb://CUSTOMER-MANAGEMENT-SERVICE
          predicates:
            - Path=/customer/**
          filters:
            - name: CircuitBreaker
              args:
                name: CUSTOMER-MANAGEMENT-SERVICE
                fallback: forward:/customerServiceFallBack
        - id: order_route
          uri: lb://SALES-DEPARTMENT-SERVICE
          predicates:
            - Path=/order/**
        - id: bike_route
          uri: lb://MANUFACTURING-DEPARTMENT-SERVICE
          predicates:
            - Path=/bike/**

server:
  port: 8091

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream