spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: customer_route
          uri: lb://CUSTOMER-MANAGEMENT-SERVICE
          predicates:
            - Path=/customer/**
        - id: order_route
          uri: lb://SALES-DEPARTMENT-SERVICE
          predicates:
            - Path=/order/**
        - id: bike_route
          uri: lb://MANUFACTURING-DEPARTMENT-SERVICE
          predicates:
            - Path=/bike/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka