spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: customer_route
          predicates:
            - Path=/customer/**
          filters:
            - RewritePath=/customer/(?<segment>.*), /api/v1/customer/$\{segment}
          uri: http://localhost:8081
        - id: order_route
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/(?<segment>.*), /api/v1/order/$\{segment}
          uri: http://localhost:8082
        - id: bike_route
          predicates:
            - Path=/bike/**
          filters:
            - RewritePath=/bike/(?<segment>.*), /api/v1/bike/$\{segment}
          uri: http://localhost:8083