app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5434/user_management
    username: postgres
    password: user-management
    pool-size: 30

spring:
  application:
    name: user-management-service
  zipkin:
    base-url: http://127.0.0.1:9411/

server:
  port : 8082