app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5433/customer_management
    username: postgres
    password: customer-management
    pool-size: 30

spring:
  application:
    name: customer-management-service
  zipkin:
    base-url: http://127.0.0.1:9411/

server:
  port : 8081