app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5434/user_management
    username: postgres
    password: user-management
    pool-size: 30

spring:
  application:
    name: USER-MANAGEMENT-SERVICE
  zipkin:
    base-url: http://localhost:8093/

server:
  port : 8082

jwt:
  secret-key: secretkey123456789

logging:
  file:
    name: C:/Users/stein/Desktop/project-work/ELK-Stack/logs/user-management.log
