app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5434/user_management
    username: postgres
    password: user-management
    pool-size: 30

spring:
  application:
    name: user-management-service
  zipkin:
    base-url: http://localhost:8093/

server:
  port : 8082

ribbon:
  eureka:
    enabled: true

jwt:
  secret-key: secretkey123456789