spring:
  application:
    name: eureka-service-discovery

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5

server:
  port: 8090
