# Disable Service Discovery act as a client
eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
  server:
    waitTimeInMsWhenSyncEmpty: 5

spring:
  application:
    name: eureka-service-discovery

server:
  port: 8761