spring:
  application:
    name: CONFIG-SERVER
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: .
        #git:
          #uri: C:/Users/stein/Desktop/project-work/backend/config-repository
          #clone-on-start: true

server:
  port: 8091

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8090/eureka}
      #defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}
